#!/usr/bin/env node
/** Generate TypeScript sign definitions from JSON files.

This script reads the sign JSON files (generated by tools/generate_sign_jsons.py)
and outputs web/src/engine/signs/index.ts with createSign() calls.

Usage:
    npx tsx tools/generate_engine_signs.ts
*/

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, basename } from 'path';

const SIGNS_DIR = join(process.cwd(), 'signs');
const OUTPUT_PATH = join(process.cwd(), 'web', 'src', 'engine', 'signs', 'index.ts');

interface SignJSON {
  name: string;
  twoHanded: boolean;
  extraHandMotionFloor: number | null;
  dominant: { kind: string; required: boolean; minConfidence: number };
  nondominant: { kind: string; required: boolean; minConfidence: number } | null;
  location: {
    anchor: string;
    actingHand: string;
    maxDistRatio: number;
    minDistRatio: number;
    vertical: string | null;
    below: string | null;
    useClosestApproach: boolean;
    required: boolean;
    minConfidence: number;
  };
  movement: {
    kind: string;
    actor: string;
    pivot: string;
    minTotalRotationDeg: number;
    radiusToleranceRatio: number;
    direction: number[] | null;
    minDisplacementRatio: number;
    minCycles: number;
    minAmplitudeRatio: number;
    minApproachRatio: number;
    traceTemplate: number[];
    traceToleranceDeg: number;
    gateToLocation: boolean;
    otherHandMaxMotionRatio: number | null;
    minDurationS: number;
    required: boolean;
    minConfidence: number;
  };
  orientation: {
    hand: string;
    facing: string;
    required: boolean;
    minConfidence: number;
  } | null;
  nmm: {
    blendshape: string;
    minScore: number;
    required: boolean;
    minConfidence: number;
  } | null;
}

function main() {
  const files = readdirSync(SIGNS_DIR)
    .filter(f => f.endsWith('.json') && f !== 'sign.schema.json')
    .sort();

  const signs: SignJSON[] = [];
  for (const file of files) {
    const content = readFileSync(join(SIGNS_DIR, file), 'utf-8');
    signs.push(JSON.parse(content));
  }

  let output = `// GENERATED FILE — DO NOT EDIT MANUALLY
// Source: tools/generate_sign_jsons.py → signs/*.json → this file
// Regenerate with: npx tsx tools/generate_engine_signs.ts

import { createSign, Anchor, MovementKind, PalmFacing, DOMINANT, NONDOMINANT } from '../schema';
import type { Sign } from '../schema';

`;

  for (const sign of signs) {
    output += generateSign(sign);
  }

  output += FOOTER;

  writeFileSync(OUTPUT_PATH, output);
  console.log(`Generated ${OUTPUT_PATH} with ${signs.length} signs`);
}

// Scenario groupings + the by-name registry are web-app knowledge (which world uses which sign),
// not part of a sign's definition — they live here as a static footer, not in the JSON files.
const FOOTER = `
export const COFFEE_SIGNS = [COFFEE, PLEASE, THANK_YOU, HELLO, WANT, YES, MORE, LETTER_A, LETTER_B, LETTER_C, LETTER_D, LETTER_E, LETTER_F, LETTER_G, LETTER_H, LETTER_I, LETTER_J, LETTER_K, LETTER_L, LETTER_M, LETTER_N, LETTER_O, LETTER_P, LETTER_Q, LETTER_R, LETTER_S, LETTER_T, LETTER_U, LETTER_V, LETTER_W, LETTER_X, LETTER_Y, LETTER_Z, YOU] as const;
export const HOSPITAL_SIGNS = [HELP, PAIN, MEDICINE, EMERGENCY, DOCTOR, NURSE, SICK, FEVER, WATER, BREATHE, HOSPITAL, DIZZY] as const;
export const CLASSROOM_SIGNS = [HELLO, PLEASE, THANK_YOU, TEACHER, WRITE, READ, NAME, FRIEND] as const;
export const WORLD_CUP_SIGNS = [RED, YELLOW, WIN, TEAM] as const;

export const SIGNS: Record<string, Sign> = {};
for (const s of [...COFFEE_SIGNS, ...HOSPITAL_SIGNS, ...CLASSROOM_SIGNS, ...WORLD_CUP_SIGNS]) {
  SIGNS[s.name] = s;
}
`;

function generateSign(s: SignJSON): string {
  const lines: string[] = [];
  lines.push(`export const ${s.name} = createSign({`);
  lines.push(`  name: '${s.name}', twoHanded: ${s.twoHanded},`);

  if (s.extraHandMotionFloor !== null) {
    lines.push(`  extraHandMotionFloor: ${s.extraHandMotionFloor},`);
  }

  // dominant
  lines.push(`  dominant: { kind: '${s.dominant.kind}', required: ${s.dominant.required}, minConfidence: ${s.dominant.minConfidence} },`);

  // nondominant
  if (s.nondominant) {
    lines.push(`  nondominant: { kind: '${s.nondominant.kind}', required: ${s.nondominant.required}, minConfidence: ${s.nondominant.minConfidence} },`);
  }

  // location
  const loc = s.location;
  lines.push(`  location: { anchor: Anchor.${anchorToConst(loc.anchor)}, actingHand: ${loc.actingHand.toUpperCase()}, maxDistRatio: ${loc.maxDistRatio}, required: ${loc.required}, minConfidence: ${loc.minConfidence}`);
  if (loc.minDistRatio !== 0.0) lines[lines.length - 1] += `, minDistRatio: ${loc.minDistRatio}`;
  if (loc.vertical) lines[lines.length - 1] += `, vertical: '${loc.vertical}'`;
  if (loc.below) lines[lines.length - 1] += `, below: '${loc.below}'`;
  if (loc.useClosestApproach) lines[lines.length - 1] += `, useClosestApproach: true`;
  lines[lines.length - 1] += ` },`;

  // movement
  const mov = s.movement;
  lines.push(`  movement: { kind: MovementKind.${movementKindToConst(mov.kind)}, actor: ${mov.actor.toUpperCase()}, pivot: ${mov.pivot.toUpperCase()}, minDurationS: ${mov.minDurationS}, required: ${mov.required}, minConfidence: ${mov.minConfidence}`);

  if (mov.kind === 'circular') {
    lines[lines.length - 1] += `, minTotalRotationDeg: ${mov.minTotalRotationDeg}, radiusToleranceRatio: ${mov.radiusToleranceRatio}`;
  } else if (mov.kind === 'linear') {
    if (mov.direction) {
      lines[lines.length - 1] += `, direction: [${mov.direction.join(', ')}] as [number, number]`;
    }
    lines[lines.length - 1] += `, minDisplacementRatio: ${mov.minDisplacementRatio}`;
    if (mov.gateToLocation) lines[lines.length - 1] += `, gateToLocation: true`;
  } else if (mov.kind === 'repeated') {
    lines[lines.length - 1] += `, minCycles: ${mov.minCycles}, minAmplitudeRatio: ${mov.minAmplitudeRatio}`;
  } else if (mov.kind === 'converge') {
    lines[lines.length - 1] += `, minApproachRatio: ${mov.minApproachRatio}`;
  } else if (mov.kind === 'traced') {
    lines[lines.length - 1] += `, traceTemplate: [${mov.traceTemplate.join(', ')}], traceToleranceDeg: ${mov.traceToleranceDeg}, minDisplacementRatio: ${mov.minDisplacementRatio}`;
  }
  lines[lines.length - 1] += ` },`;

  // orientation
  if (s.orientation) {
    const ori = s.orientation;
    lines.push(`  orientation: { hand: ${ori.hand.toUpperCase()}, facing: PalmFacing.${facingToConst(ori.facing)}, required: ${ori.required}, minConfidence: ${ori.minConfidence} },`);
  }

  // nmm
  if (s.nmm) {
    const nmm = s.nmm;
    lines.push(`  nmm: { blendshape: '${nmm.blendshape}', minScore: ${nmm.minScore}, required: ${nmm.required}, minConfidence: ${nmm.minConfidence} },`);
  }

  lines.push(`});`);
  lines.push('');

  return lines.join('\n');
}

function anchorToConst(anchor: string): string {
  const map: Record<string, string> = {
    'other_hand': 'OTHER_HAND',
    'neutral_space': 'NEUTRAL_SPACE',
    'chest': 'CHEST',
    'chin': 'CHIN',
    'forehead': 'FOREHEAD',
    'belly': 'BELLY',
    'shoulder': 'SHOULDER',
  };
  return map[anchor] || anchor.toUpperCase();
}

function movementKindToConst(kind: string): string {
  const map: Record<string, string> = {
    'none': 'NONE',
    'linear': 'LINEAR',
    'circular': 'CIRCULAR',
    'repeated': 'REPEATED',
    'converge': 'CONVERGE',
    'traced': 'TRACED',
  };
  return map[kind] || kind.toUpperCase();
}

function facingToConst(facing: string): string {
  return facing.toUpperCase();
}

main();